from dictogram import Dictogram
import sys

# module for generating histograms from a list tokens
# Currently only creating histograms in the form of dictionaries, or dictograms

def create_histogram(tokenized_words):
   ''' Takes in a tokenized list (generated by split_text_file.py)
   of the text and will return a dictogram object '''
   return Dictogram(tokenized_words)

if __name__ == "__main__":
    print(create_histogram('fish.txt'))
